### ISSUE TITLE
Compability with Kali Linux on USBarmory

### ISSUE THREAD

**Issue by MoD01** [qlyoung/armory-keyboard#2]
Hi,

have you tested it on Kali Linux ? 
I cannot get it work but  [this here](https://github.com/crmulliner/hidemulation) is working fine.

The HID device is available and with hidemulation (see link above) I can print to the USB host. I tested it on Windows and Mac host - no success.

PS: The example script is working (prints the text to the console. The only thing not working is the output via the USB HID device in /dev/..

Looking forward for your answer :)

**Comment by qlyoung** [comment]
I need more information in order to help you. Helpful things would include:

- The exact command you executed
- dmesg output during / after execution
- ls /dev/
- A link to the Kali Linux image you are using for the USBArmory

**Comment by MoD01** [comment]
PS: When using your `./hid-ecm.sh` script I can successfully print to HID USB output with `string2hid` from [this repository](https://github.com/crmulliner/hidemulation), but not with your `type`.



## Called commands
> The exact command you executed
```
git clone https://github.com/qlyoung/armory-keyboard.git
cd /root/armory-keyboard 
make && cp build/type ./
dmesg > dmesg_1
./hid-ecm.sh #init the HID device
dmesg > dmesg_2
ls /dev/hid* > hid_info_1
./type -s examples/example.txt -l layouts/english-103P.layout # the text is printed to stdout (the console it is executed) but not via usb hid device
dmesg > dmesg_3 # during execution of command above
dmesg > dmesg_4 # after execution
```

## Kali Image

> A link to the Kali Linux image you are using for the USBArmory

 - [this one](https://www.offensive-security.com/kali-linux-arm-images/) (`USBArmory by InversePath`)

## dmesg_1 (at the beginning)

> dmesg output
```snip, provided as requested but removed by qlyoung for brevity```

**Comment by qlyoung** [comment]
I just installed the Kali Linux image you used and it worked fine. Asciinema:
https://asciinema.org/a/8iypzb1w64d8hnhaoc5k7ylwy

My guess is that you had your cursor focused in the window you were ssh'd to the usbarmory with, and saw both the echoed output from the tool itself *and* the input from the usbarmory being typed into the same window from your host machine.

Please also note that the example script is designed to be run inside tmux, as you'll notice in the screencast above.

Closing this, feel free to reopen if you have additional issues.
