### ISSUE TITLE
CDC ECM Driver not automatically detected by Windows

### ISSUE THREAD

**Issue by MoD01** [qlyoung/armory-keyboard#3]
> Linux with kernel versions newer than 2.6.22 have fully support for CDC-ECM. Mac OS X supports CDC-ECM natively from version 10.4 (Tiger). For Windows a CDC-ECM driver is required.

Source: https://www.segger.com/emusb-device-cdc-ecm.html

The CDC ECM Driver works very well with MacOS but in Windows you have to install it manually. Are you aware of any USB HID+Ethernet driver available that can be used without installing the drivers manually (plug&play) - platform independent?

**Comment by qlyoung** [comment]
From the two issues you have opened, it sounds like you already know what the problem is:

> The CDC ECM Driver works very well with MacOS but in Windows you have to install it manually.

So we have established that this is a problem with Windows.

> Are you aware of any USB HID+Ethernet driver available that can be used without installing the drivers manually (plug&play) - platform independent?

This comment says to me that you don't quite understand what a device driver is. Can you clarify this part of the question?
